### ISSUE TITLE
AUTOINCREMENT

### ISSUE THREAD

**Issue by Kokrra** [mitchtabian/SQLiteSaveUserData#1]
After downloading i run this code and i found out that when you have written auto increment id you have written wrong and the data are not saved.
 just replace AUTOCRIMENT to AUTOINCREMENT

 public void onCreate(SQLiteDatabase db) {
        String createTable = "CREATE TABLE " + TABLE_NAME + " (ID INTEGER PRIMARY KEY AUTOINCREMENT, " +
                " NAME TEXT, EMAIL TEXT, TVSHOW TEXT)";
        db.execSQL(createTable);
    }

**Comment by mitchtabian** [comment]
Thanks, I will fix this issue tonight when I'm off work.
